//! SymbolContext — per-symbol accessor returned by `ctx.sym("SYMBOL")` in multi-symbol scripts.
//!
//! Provides OHLCV getters, indicators, and strategy helpers scoped to a specific
//! symbol's data. Lighter than `BarContext` — no portfolio state, no cross-symbol
//! data, no custom series. Just the data needed to read prices, check indicators,
//! and build options trades for one symbol.

use std::sync::Arc;

use chrono::NaiveDateTime;
use rhai::Dynamic;

use super::config::OhlcvBar;
use crate::scripting::helpers::{build_strategy_from_legs, wrap_spread_action};
use crate::scripting::indicators::IndicatorStore;
use crate::scripting::options_cache::DatePartitionedOptions;

/// Per-symbol context returned by `ctx.sym("SYMBOL")`.
///
/// Contains the symbol's OHLCV bar at the current date, indicator store,
/// and options data — everything needed to read data and build trades.
#[derive(Clone)]
pub struct SymbolContext {
    pub symbol: String,
    pub datetime: NaiveDateTime,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub bar_idx: usize,
    pub indicator_store: Arc<IndicatorStore>,
    pub price_history: Arc<Vec<OhlcvBar>>,
    pub options_by_date: Option<Arc<DatePartitionedOptions>>,
}

// ---------------------------------------------------------------------------
// Rhai property getters
// ---------------------------------------------------------------------------

impl SymbolContext {
    pub fn get_symbol(&mut self) -> String {
        self.symbol.clone()
    }
    pub fn get_open(&mut self) -> f64 {
        self.open
    }
    pub fn get_high(&mut self) -> f64 {
        self.high
    }
    pub fn get_low(&mut self) -> f64 {
        self.low
    }
    pub fn get_close(&mut self) -> f64 {
        self.close
    }
    pub fn get_volume(&mut self) -> f64 {
        self.volume
    }
    pub fn get_bar_idx(&mut self) -> i64 {
        self.bar_idx as i64
    }
    pub fn get_date(&mut self) -> String {
        self.datetime.date().to_string()
    }
    pub fn get_datetime(&mut self) -> String {
        self.datetime.to_string()
    }
}

// ---------------------------------------------------------------------------
// Indicator methods — generated by macro (shared with BarContext)
// ---------------------------------------------------------------------------

impl_indicators!(SymbolContext);

// ---------------------------------------------------------------------------
// Historical bar lookback
// ---------------------------------------------------------------------------

impl SymbolContext {
    pub fn high_at(&self, n: i64) -> Dynamic {
        self.bar_at_offset(n)
            .map_or(Dynamic::UNIT, |b| Dynamic::from(b.high))
    }
    pub fn low_at(&self, n: i64) -> Dynamic {
        self.bar_at_offset(n)
            .map_or(Dynamic::UNIT, |b| Dynamic::from(b.low))
    }
    pub fn open_at(&self, n: i64) -> Dynamic {
        self.bar_at_offset(n)
            .map_or(Dynamic::UNIT, |b| Dynamic::from(b.open))
    }
    pub fn close_at(&self, n: i64) -> Dynamic {
        self.bar_at_offset(n)
            .map_or(Dynamic::UNIT, |b| Dynamic::from(b.close))
    }

    fn bar_at_offset(&self, n: i64) -> Option<&OhlcvBar> {
        if n < 0 {
            return None;
        }
        if n == 0 {
            return self.price_history.get(self.bar_idx);
        }
        let idx = self.bar_idx.checked_sub(n as usize)?;
        self.price_history.get(idx)
    }
}

// ---------------------------------------------------------------------------
// Options strategy helpers — build_strategy + wrap, then macro for named strategies
// ---------------------------------------------------------------------------

impl SymbolContext {
    pub fn build_strategy(&mut self, legs: rhai::Array) -> Dynamic {
        build_strategy_from_legs(
            legs,
            &self.options_by_date,
            self.datetime,
            Some(&self.symbol),
        )
    }

    /// Wrap a resolved spread into an action map for SymbolContext.
    pub fn wrap_strategy_action(spread: Dynamic) -> Dynamic {
        wrap_spread_action(spread)
    }
}

// Strategy methods generated by macro — single source of truth for both
// BarContext and SymbolContext.
impl_options_strategies!(SymbolContext);
