//! Rhai engine configuration, sandboxing, and type/function registration.

use rhai::{Dynamic, Engine};

use super::dsl;
use super::helpers;
use super::types::{BarContext, PortfolioState, ScriptPosition, SymbolContext};

/// Build a sandboxed Rhai engine with all custom types and functions registered.
#[must_use]
pub fn build_engine() -> Engine {
    let mut engine = Engine::new();

    // Safety limits
    engine.set_max_operations(1_000_000); // ~10s of Rhai-level compute
    engine.set_max_expr_depths(64, 64); // expression nesting depth
    engine.set_max_call_levels(32); // recursion depth
    engine.set_max_string_size(10_000); // 10KB strings
    engine.set_max_array_size(10_000); // array elements
    engine.set_max_map_size(500); // map properties

    // Redirect print() to tracing (prevents stdout corruption in stdio MCP transport)
    engine.on_print(|msg| {
        tracing::debug!(script_output = msg);
    });
    engine.on_debug(|msg, source, pos| {
        tracing::debug!(
            script_debug = msg,
            source = source.unwrap_or(""),
            line = pos.line().unwrap_or(0),
        );
    });

    // Stub extern_symbol(name, default, description) — no-op in the base engine.
    // The real implementation is registered by run_script_backtest / validate_script
    // which overrides this with param resolution. This stub exists so scripts
    // can compile without error when using build_engine() directly (e.g., DSL tests).
    engine.register_fn(
        "extern_symbol",
        |_name: &str, default: rhai::Dynamic, _desc: &str| -> rhai::Dynamic { default },
    );

    // Register custom types
    register_bar_context(&mut engine);
    register_symbol_context(&mut engine);
    register_script_position(&mut engine);
    register_portfolio_state(&mut engine);

    // Register global helper functions
    register_global_helpers(&mut engine);

    // Register high-level action helpers and strategy constructors
    register_action_helpers(&mut engine);
    register_strategy_helpers(&mut engine);

    // Register DSL custom syntax (buy N shares, exit_position "reason", hold, etc.)
    dsl::register_dsl_syntax(&mut engine);

    engine
}

/// Register `BarContext` as a Rhai custom type with getters and methods.
fn register_bar_context(engine: &mut Engine) {
    // Property getters for current bar data
    engine.register_get("date", BarContext::get_date);
    engine.register_get("datetime", BarContext::get_datetime);
    engine.register_get("open", BarContext::get_open);
    engine.register_get("high", BarContext::get_high);
    engine.register_get("low", BarContext::get_low);
    engine.register_get("close", BarContext::get_close);
    engine.register_get("volume", BarContext::get_volume);
    engine.register_get("adjusted_close", BarContext::get_adjusted_close);
    engine.register_get("bar_idx", BarContext::get_bar_idx);

    // Portfolio getters
    engine.register_get("cash", BarContext::get_cash);
    engine.register_get("equity", BarContext::get_equity);

    // Position awareness (next-bar execution model)
    engine.register_get("market_position", BarContext::get_market_position);
    engine.register_get("entry_price", BarContext::get_entry_price);
    engine.register_get("bars_since_entry", BarContext::get_bars_since_entry);
    engine.register_get("current_shares", BarContext::get_current_shares);
    engine.register_get("open_profit", BarContext::get_open_profit);
    engine.register_get("max_profit", BarContext::get_max_profit);
    engine.register_get("max_loss", BarContext::get_max_loss);
    engine.register_get("pending_orders_count", BarContext::get_pending_orders_count);

    // Methods
    engine.register_fn("price", BarContext::price);
    engine.register_fn("positions", BarContext::get_positions);
    engine.register_get("position_count", BarContext::position_count);
    engine.register_fn("has_positions", BarContext::has_positions);

    // Indicators — generated by macro (shared with SymbolContext)
    register_indicators!(engine, BarContext);

    // Date/time
    engine.register_fn("day_of_week", BarContext::day_of_week);
    engine.register_fn("month", BarContext::month);
    engine.register_fn("day_of_month", BarContext::day_of_month);
    engine.register_fn("hour", BarContext::hour);
    engine.register_fn("minute", BarContext::minute);
    engine.register_fn("week_of_year", BarContext::week_of_year);
    engine.register_fn("time", BarContext::time);
    engine.register_fn("is_first_bar", BarContext::is_first_bar);
    engine.register_fn("is_last_bar", BarContext::is_last_bar);
    engine.register_fn("is_expiry_week", BarContext::is_expiry_week);
    engine.register_fn("is_quarter_end", BarContext::is_quarter_end);
    engine.register_fn("trading_days_left", BarContext::trading_days_left);
    engine.register_fn("minutes_since_open", BarContext::minutes_since_open);

    // Indicator lookback (for crossover detection)
    engine.register_fn("sma_at", BarContext::sma_at);
    engine.register_fn("ema_at", BarContext::ema_at);
    engine.register_fn("rsi_at", BarContext::rsi_at);
    engine.register_fn("indicator_at", BarContext::indicator_at);
    engine.register_fn("crossed_above", BarContext::crossed_above);
    engine.register_fn("crossed_below", BarContext::crossed_below);

    // Multi-param indicator overloads
    engine.register_fn("macd_line_custom", BarContext::macd_line_custom);
    engine.register_fn("macd_signal_custom", BarContext::macd_signal_custom);
    engine.register_fn("macd_hist_custom", BarContext::macd_hist_custom);
    engine.register_fn("bbands_upper_custom", BarContext::bbands_upper_custom);
    engine.register_fn("bbands_mid_custom", BarContext::bbands_mid_custom);
    engine.register_fn("bbands_lower_custom", BarContext::bbands_lower_custom);
    engine.register_fn("stochastic_custom", BarContext::stochastic_custom);

    // Historical bar lookback (MQL4-inspired)
    engine.register_fn("high", |ctx: &mut BarContext, n: i64| -> Dynamic {
        ctx.high_at(n)
    });
    engine.register_fn("low", |ctx: &mut BarContext, n: i64| -> Dynamic {
        ctx.low_at(n)
    });
    engine.register_fn("open", |ctx: &mut BarContext, n: i64| -> Dynamic {
        ctx.open_at(n)
    });
    engine.register_fn("close", |ctx: &mut BarContext, n: i64| -> Dynamic {
        ctx.close_at(n)
    });
    engine.register_fn("volume", |ctx: &mut BarContext, n: i64| -> Dynamic {
        ctx.volume_at(n)
    });

    // Range queries (MQL4-inspired iHighest/iLowest)
    engine.register_fn("highest_high", BarContext::highest_high);
    engine.register_fn("lowest_low", BarContext::lowest_low);
    engine.register_fn("highest_close", BarContext::highest_close);
    engine.register_fn("lowest_close", BarContext::lowest_close);

    // Portfolio methods
    engine.register_get("unrealized_pnl", BarContext::get_unrealized_pnl);
    engine.register_get("realized_pnl", BarContext::get_realized_pnl);
    engine.register_get("total_exposure", BarContext::get_total_exposure);

    // Portfolio namespace
    engine.register_get("portfolio", BarContext::get_portfolio);

    // Cross-symbol data
    engine.register_fn("price_of", BarContext::price_of);
    engine.register_fn("price_of_col", BarContext::price_of_col);

    // Multi-symbol portfolio: ctx.sym("SPY") returns a SymbolContext
    engine.register_fn("sym", BarContext::sym);
    engine.register_fn("symbols", BarContext::symbols);

    // Custom series plotting
    engine.register_fn("plot", BarContext::plot);
    engine.register_fn("plot_with", BarContext::plot_with);
}

/// Register `SymbolContext` as a Rhai custom type with getters and methods.
///
/// `SymbolContext` is returned by `ctx.sym("SYMBOL")` in multi-symbol scripts.
/// It provides OHLCV getters, indicators, and strategy helpers scoped to one symbol.
fn register_symbol_context(engine: &mut Engine) {
    // Property getters
    engine.register_get("symbol", SymbolContext::get_symbol);
    engine.register_get("open", SymbolContext::get_open);
    engine.register_get("high", SymbolContext::get_high);
    engine.register_get("low", SymbolContext::get_low);
    engine.register_get("close", SymbolContext::get_close);
    engine.register_get("volume", SymbolContext::get_volume);
    engine.register_get("bar_idx", SymbolContext::get_bar_idx);
    engine.register_get("date", SymbolContext::get_date);
    engine.register_get("datetime", SymbolContext::get_datetime);

    // Indicators — generated by macro (shared with BarContext)
    register_indicators!(engine, SymbolContext);

    // Position sizing helpers (use price from this symbol's bar)
    engine.register_fn(
        "size_by_equity",
        |ctx: &mut SymbolContext, fraction: f64, equity: f64| -> i64 {
            if ctx.close <= 0.0 {
                return 0;
            }
            ((equity * fraction) / ctx.close).floor() as i64
        },
    );

    // Historical bar lookback
    engine.register_fn("high", |ctx: &mut SymbolContext, n: i64| -> Dynamic {
        ctx.high_at(n)
    });
    engine.register_fn("low", |ctx: &mut SymbolContext, n: i64| -> Dynamic {
        ctx.low_at(n)
    });
    engine.register_fn("open", |ctx: &mut SymbolContext, n: i64| -> Dynamic {
        ctx.open_at(n)
    });
    engine.register_fn("close", |ctx: &mut SymbolContext, n: i64| -> Dynamic {
        ctx.close_at(n)
    });

    // Options strategy helpers — generated by macro (shared with BarContext)
    register_options_strategies!(engine, SymbolContext);
}

/// Register `ScriptPosition` as a Rhai custom type with getters.
fn register_script_position(engine: &mut Engine) {
    engine.register_get("id", ScriptPosition::get_id);
    engine.register_get("symbol", ScriptPosition::get_symbol);
    engine.register_get("entry_date", ScriptPosition::get_entry_date);
    engine.register_get("expiration", ScriptPosition::get_expiration);
    engine.register_get("dte", ScriptPosition::get_dte);
    engine.register_get("entry_cost", ScriptPosition::get_entry_cost);
    engine.register_get("unrealized_pnl", ScriptPosition::get_unrealized_pnl);
    engine.register_get("pnl_pct", ScriptPosition::get_pnl_pct);
    engine.register_get("days_held", ScriptPosition::get_days_held);
    engine.register_get("legs", ScriptPosition::get_legs);
    engine.register_get("side", ScriptPosition::get_side);
    engine.register_get("is_options", ScriptPosition::get_is_options);
    engine.register_get("is_stock", ScriptPosition::get_is_stock);
    engine.register_get("source", ScriptPosition::get_source);
}

/// Register `PortfolioState` as a Rhai custom type with property getters.
fn register_portfolio_state(engine: &mut Engine) {
    engine.register_get("cash", PortfolioState::get_cash);
    engine.register_get("equity", PortfolioState::get_equity);
    engine.register_get("unrealized_pnl", PortfolioState::get_unrealized_pnl);
    engine.register_get("realized_pnl", PortfolioState::get_realized_pnl);
    engine.register_get("total_exposure", PortfolioState::get_total_exposure);
    engine.register_get("exposure_pct", PortfolioState::get_exposure_pct);
    engine.register_get("net_delta", PortfolioState::get_net_delta);
    engine.register_get("long_delta", PortfolioState::get_long_delta);
    engine.register_get("short_delta", PortfolioState::get_short_delta);
    engine.register_get("position_count", PortfolioState::get_position_count);
    engine.register_get("long_count", PortfolioState::get_long_count);
    engine.register_get("short_count", PortfolioState::get_short_count);
    engine.register_get("max_position_pnl", PortfolioState::get_max_position_pnl);
    engine.register_get("min_position_pnl", PortfolioState::get_min_position_pnl);
    engine.register_get("drawdown", PortfolioState::get_drawdown);
    engine.register_get("peak_equity", PortfolioState::get_peak_equity);
}

/// Register global helper functions available in all scripts.
fn register_global_helpers(engine: &mut Engine) {
    engine.register_fn("abs", |x: f64| x.abs());
    engine.register_fn("max", |a: f64, b: f64| a.max(b));
    engine.register_fn("min", |a: f64, b: f64| a.min(b));
    engine.register_fn("round", |x: f64, decimals: i64| {
        let factor = 10_f64.powi(decimals as i32);
        (x * factor).round() / factor
    });
    engine.register_fn("floor", |x: f64| x.floor());
    engine.register_fn("ceil", |x: f64| x.ceil());
}

/// Register global action helper functions (hold_position, close_position, etc.).
fn register_action_helpers(engine: &mut Engine) {
    engine.register_fn("hold_position", helpers::hold_position);
    engine.register_fn("close_position", helpers::close_position);
    engine.register_fn("close_position_id", helpers::close_position_id);
    engine.register_fn("stop_backtest", helpers::stop_backtest);
    engine.register_fn("buy_stock", helpers::buy_stock);
    engine.register_fn("sell_stock", helpers::sell_stock);

    // Order-type helpers (next-bar execution model)
    engine.register_fn("buy_limit", helpers::buy_limit);
    engine.register_fn("buy_stop", helpers::buy_stop);
    engine.register_fn("buy_stop_limit", helpers::buy_stop_limit);
    engine.register_fn("sell_limit", helpers::sell_limit);
    engine.register_fn("sell_stop", helpers::sell_stop);
    engine.register_fn("sell_stop_limit", helpers::sell_stop_limit);
    engine.register_fn("cancel_orders", helpers::cancel_orders as fn() -> Dynamic);
    engine.register_fn("cancel_orders", helpers::cancel_orders_by_signal);
}

/// Register strategy helper methods on `BarContext`.
fn register_strategy_helpers(engine: &mut Engine) {
    // Position sizing
    engine.register_fn("size_by_equity", BarContext::size_by_equity);
    engine.register_fn("size_by_risk", BarContext::size_by_risk);
    engine.register_fn("size_by_volatility", BarContext::size_by_volatility);
    engine.register_fn("size_by_kelly", BarContext::size_by_kelly);

    // Options strategies — generated by macro (shared with SymbolContext)
    register_options_strategies!(engine, BarContext);
}
